version: '3'
services:
    tomcat:
        build: 
            context: .
            dockerfile: tomcat-dockerfile
        image: tomcat-docker:latest
        ports:
            - "8080"
        restart: always
    eclipse:
        build:
            context: .
            dockerfile: eclipse-dockerfile
        image: eclipse-docker:latest
        volumes:
            - "$HOME/.Xauthority:/root/.Xauthority:rw"
            - "/tmp/.X11-unix:/tmp/.X11-unix"
        network_mode: "host"
        environment: 
            - DISPLAY
        restart: always
    spring:
        build:
            context: .
            dockerfile: spring-dockerfile            
        restart: always
    mysql:
        image: mysql:5.7
        ports: 
            - "8081"
        restart: always
