version: '3'
services:
    tomcat:
        build: 
            context: .
            dockerfile: tomcat-dockerfile
        image: tomcat-docker:latest
        ports:
            - "8080"
        restart: always
    eclipse:
        build:
            context: .
            dockerfile: eclipse-dockerfile
        image: eclipse-docker:latest
        environment:
            - net=host
            - DISPLAY=$DISPLAY
            - VOLUME=$HOME/.Xauthority:/root/.Xauthority:rw
    spring:
        build:
            context: .
            dockerfile: spring-dockerfile            
        restart: always
    mysql:
        image: mysql/mysql:8.0
        ports: 
            - "8081"
        restart: always
