FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt upgrade -y
RUN apt-get install apt-utils sudo -y

# INSTALL UTILITIES WGET AND TAR
RUN apt-get install wget tar -y

# INSTALL MAVEN GRADLE AND JDK
RUN apt-get install maven gradle default-jdk -y

# INSTALL ECLIPSE
RUN wget http://mirror.tspu.ru/eclipse/technology/epp/downloads/release/2020-06/R/eclipse-jee-2020-06-R-linux-gtk-x86_64.tar.gz -P /opt
RUN cd /opt && tar xvzf eclipse-jee-2020-06-R-linux-gtk-x86_64.tar.gz

# INSTALL LIBGTK3 FOR ECLIPSE
RUN apt-get install "libgtk-3*" "libgtksourceview-3.0*" -y

# INSTALL SPRING LIBRARIES
RUN mkdir "/usr/local/spring-v5.2.7"
RUN wget "https://repo.spring.io/release/org/springframework/spring/5.2.7.RELEASE/spring-5.2.7.RELEASE-dist.zip" -P "/usr/local/spring-v5.2.7/"
RUN cd "/usr/local/spring-v5.2.7/" && unzip "spring-5.2.7.RELEASE-dist.zip"

#INSTALL TOMCAT
RUN mkdir /usr/local/apache-tomcat-v8.5.57
RUN wget http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.57/bin/apache-tomcat-8.5.57.tar.gz -O /tmp/apache-tomcat-v8.5.57.tar.gz
RUN cd /tmp && tar xvfz apache-tomcat-v8.5.57.tar.gz
RUN cp -Rv /tmp/apache-tomcat-8.5.57/* /usr/local/apache-tomcat-v8.5.57/
EXPOSE 8080

#CREATE ENVIRONMENT VARIABLES
RUN echo "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" | cat >> /root/.bashrc
RUN echo "export JAVA_EXECUTABLE_HOME=\$JAVA_HOME/bin" | cat >> /root/.bashrc

# CREATE RUN SCRIPT
RUN touch startup.sh
RUN chmod +x startup.sh
RUN echo "if [ -z $\{DISPLAY+x\} ]; then\n\t/usr/local/apache-tomcat-v8.5.57/bin/catalina.sh run;\nelse\n\t/opt/eclipse/eclipse&\n\t/usr/local/apache-tomcat-v8.5.57/bin/catalina.sh run\nfi" | cat > startup.sh
RUN sed -i 's/\\//g' startup.sh


ENTRYPOINT ./startup.sh
