FROM ubuntu:latest

ENV LANG en_US.UTF-8

RUN apt-get update && \
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      locales && \
      echo "$LANG UTF-8" >> /etc/locale.gen && \
      locale-gen && \
    env DEBIAN_FRONTEND=noninteractive apt-get install -y \
      at-spi2-core \
      dbus \
      dbus-x11 \
      procps \
      psutils \
      systemd && \
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      gnome-session && \
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      cheese \
      gedit \
      gnome-control-center \
      gnome-terminal \
      gnome-tweak-tool \
      nautilus && \
    env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      gnome-shell-extension-dash-to-panel \
      gnome-shell-extension-desktop-icons \
      gnome-shell-extension-weather

RUN apt install wget -y

RUN wget https://eclipse.bluemix.net/packages/2020-06/data/eclipse-java-2020-06-R-linux-gtk-x86_64.tar.gz -P /opt/eclipse-java

RUN tar -xvzf /opt/eclipse-java/eclipse-java-2020-06-R-linux-gtk-x86_64.tar.gz -C /opt/eclipse-java

CMD gnome-session
