FROM ubuntu:latest

LABEL MAINTAINER="kesarling"

RUN apt update
RUN apt upgrade -y
RUN apt-get install mysql-server-8.0 mysql-client-8.0 -y
RUN service mysql start
# RUN SECURE_MYSQL=$(expect -c "\
# 		spawn mysql_secure_installation\
# 		expect \"Enter current password for root (enter for none):\"\
# 		send \"$MYSQL\r\"\
# 		expect \"Change the root password?\"\
# 		send \"n\r\"\
# 		expect \"Remove anonymous users?\"\
# 		send \"y\r\"\
# 		expect \"Disallow root login remotely?\"\
# 		send \"y\r\"\
# 		expect \"Remove test database and access to it?\"\
# 		send \"y\r\"\
# 		expect \"Reload privilege tables now?\"\
# 		send \"y\r\"\
# 		expect eof\
# 	")
